name: Docker Image CI VM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: 'read'
  packages: 'write'
  
env:
  DOCKER_IMAGE_NAME: joeting91/pythonblog
  TAG: latest
  AZURE_WEBAPP_NAME: blogapp2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}   
        
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
      
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
               IMAGE_NAME='${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}  ' \
               CONTAINER=$(docker ps | grep $IMAGE_NAME | awk '{print $1;}') \
               docker kill $CONTAINER \
               docker pull $IMAGE_NAME \
               docker run -d -p 80:80 $IMAGE_NAME  
          host: ${{secrets.SSH_HOST}} 
          user: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}} 
          
          
        
