name: Docker Image CI VM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: 'read'
  packages: 'write'
  
env:
  DOCKER_IMAGE_NAME: joeting91/pythonblog
  TAG: latest
  AZURE_WEBAPP_NAME: blogapp2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}   
        
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Deploy to Azure VM
      uses: ssh-actions/ssh@v3
      with:
         ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
         host: ${{secrets.SSH_HOST}} 
         username: ${{secrets.SSH_USERNAME}}
         script: |
            cd ~
            sh script.sh

  
  

          
        
